package dev.jonpoulton.catalog.gradle.internal.writer

import com.google.common.truth.Truth.assertThat
import dev.jonpoulton.catalog.gradle.CatalogParameterNaming
import dev.jonpoulton.catalog.gradle.GenerateResourcesTask
import dev.jonpoulton.catalog.gradle.internal.ResourceEntry
import dev.jonpoulton.catalog.gradle.test.isEqualToKotlin
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.nio.charset.Charset

class ColorCatalogWriterTest {
  @get:Rule
  var folder = TemporaryFolder()

  private val resources = listOf(
    ResourceEntry.XmlItem.Color(file = File("."), name = "color_1", docs = "Color 1 docs"),
    ResourceEntry.XmlItem.Color(file = File("."), name = "color_2", docs = null),
  )

  private lateinit var codegenDestination: File
  private lateinit var codegenFile: File

  private fun colorCatalogWriter(
    packageName: String = "com.example",
    internal: Boolean = false,
    prefix: String = "",
    parameterNaming: CatalogParameterNaming = CatalogParameterNaming.Arg,
  ) = ColorCatalogWriter(config = GenerateResourcesTask.TaskConfig(packageName, internal, prefix, parameterNaming))

  @Before
  fun setUp() {
    codegenDestination = folder.newFolder()
    codegenFile = File("${codegenDestination.absolutePath}/com/example/Colors.kt")
  }

  @Test
  fun `GIVEN defaults THEN generate public properties with no prefix`() {
    colorCatalogWriter().write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/Catalog
        @file:Suppress("NOTHING_TO_INLINE")

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.graphics.Color
        import androidx.compose.ui.res.colorResource
        import kotlin.Suppress

        public object Colors {
          /**
           * Color 1 docs
           */
          public inline val color1: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_1)

          public inline val color2: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_2)
        }

      """,
    )
  }

  @Test
  fun `GIVEN internal THEN generate internal properties with no prefix`() {
    colorCatalogWriter(internal = true).write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/Catalog
        @file:Suppress("NOTHING_TO_INLINE")

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.graphics.Color
        import androidx.compose.ui.res.colorResource
        import kotlin.Suppress

        internal object Colors {
          /**
           * Color 1 docs
           */
          internal inline val color1: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_1)

          internal inline val color2: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_2)
        }

      """,
    )
  }

  @Test
  fun `GIVEN prefix THEN generate public properties with prefix`() {
    colorCatalogWriter(prefix = "Something").write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/Catalog
        @file:Suppress("NOTHING_TO_INLINE")

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.graphics.Color
        import androidx.compose.ui.res.colorResource
        import kotlin.Suppress

        public object SomethingColors {
          /**
           * Color 1 docs
           */
          public inline val color1: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_1)

          public inline val color2: Color
            @Composable
            @ReadOnlyComposable
            get() = colorResource(R.color.color_2)
        }

      """,
    )
  }
}
