package dev.jonpoulton.catalog.gradle.internal.writer

import com.google.common.truth.Truth.assertThat
import dev.jonpoulton.catalog.gradle.CatalogParameterNaming
import dev.jonpoulton.catalog.gradle.GenerateResourcesTask
import dev.jonpoulton.catalog.gradle.internal.ResourceEntry
import dev.jonpoulton.catalog.gradle.test.isEqualToKotlin
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.nio.charset.Charset

class DimenCatalogWriterTest {
  @get:Rule
  var folder = TemporaryFolder()

  private lateinit var codegenDestination: File
  private lateinit var codegenFile: File

  private val resources = listOf(
    ResourceEntry.XmlItem.Dimen(file = File("."), name = "dimen_1", docs = "Dimen 1 docs"),
    ResourceEntry.XmlItem.Dimen(file = File("."), name = "dimen_2", docs = null),
  )

  private fun dimenCatalogWriter(
    packageName: String = "com.example",
    internal: Boolean = false,
    prefix: String = "",
    parameterNaming: CatalogParameterNaming = CatalogParameterNaming.Arg,
  ) = DimenCatalogWriter(config = GenerateResourcesTask.TaskConfig(packageName, internal, prefix, parameterNaming))

  @Before
  fun setUp() {
    codegenDestination = folder.newFolder()
    codegenFile = File("${codegenDestination.absolutePath}/com/example/Dimens.kt")
  }

  @Test
  fun `GIVEN defaults THEN generate public properties with no prefix`() {
    dimenCatalogWriter().write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/catalog

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.res.dimensionResource
        import androidx.compose.ui.unit.Dp
        import kotlin.Suppress

        public object Dimens {
          /**
           * Dimen 1 docs
           */
          public val dimen1: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_1)

          public val dimen2: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_2)
        }

      """,
    )
  }

  @Test
  fun `GIVEN internal THEN generate internal properties with no prefix`() {
    dimenCatalogWriter(internal = true).write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/catalog

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.res.dimensionResource
        import androidx.compose.ui.unit.Dp
        import kotlin.Suppress

        internal object Dimens {
          /**
           * Dimen 1 docs
           */
          internal val dimen1: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_1)

          internal val dimen2: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_2)
        }

      """,
    )
  }

  @Test
  fun `GIVEN prefix THEN generate public properties with prefix`() {
    dimenCatalogWriter(prefix = "Something").write(resources, codegenDestination)
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualToKotlin(
      """
        // DO NOT EDIT: Auto-generated by Catalog. https://github.com/jonapoul/catalog

        package com.example

        import androidx.compose.runtime.Composable
        import androidx.compose.runtime.ReadOnlyComposable
        import androidx.compose.ui.res.dimensionResource
        import androidx.compose.ui.unit.Dp
        import kotlin.Suppress

        public object SomethingDimens {
          /**
           * Dimen 1 docs
           */
          public val dimen1: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_1)

          public val dimen2: Dp
            @Composable
            @ReadOnlyComposable
            get() = dimensionResource(R.dimen.dimen_2)
        }

      """,
    )
  }
}
