[versions]
agp = "8.13.1"
kotlin = "2.2.20"

[libraries]
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }
ktfmt = { module = "com.facebook:ktfmt", version = "0.64" } # only used in ktfmt.sh
test-junit = { module = "junit:junit", version = "4.13.2" }
test-truth = { module = "com.google.truth:truth", version = "1.4.5" }

[plugins]
agp-kmp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.1" }
jetbrainsCompose = { id = "org.jetbrains.compose", version = "1.9.3" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
